### ISSUE TITLE
Updated README.md.

### ISSUE THREAD

**Issue by akath20** [kristenmills/torque-react#5]
With the release of 3.0, there are some questions left unanswered by the README and the demo. It appears that `TorqueSlide` was removed and there is just `TorqueSlides`, but does that remove the ability to add different durations for each slide?

**Comment by kristenmills** [comment]
Dylan rewrote a lot of this....let me take a look

**Comment by kristenmills** [comment]
I fixed it to add torque slide in duration. Install 3.1.0

**Comment by akath20** [comment]
Thank you, Kristen! I will try it out when I can on GTV.
