### ISSUE TITLE
Upgrade & Support React 16

### ISSUE THREAD

**Issue by billdybas** [kristenmills/torque-react#6]
Currently uses React 15. `peerDependencies` are also pinned to React 15.

**Comment by kristenmills** [comment]
@billdybas if you wanna submit it a PR to fix it, feel free. Otherwise I'll get to it sometime this week.

**Comment by billdybas** [comment]
@kristenmills I can take a look. Just noticed the npm warnings when I was upgrading the OneRepo's version and wanted to call it out. No rush.

**Comment by kristenmills** [comment]
I changed the peer dependencies to >= 15. Published as 3.1.1
